version: "2.1"
services:
  bot:
    image: egormit/happy-birthday-bot
    container_name: bot
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_HOST=bot_db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - RABBIT_HOST=rabbitmq
    networks:
      - bot-network
    ports:
      - "8081:8081"
    restart: always

  db:
    image: postgres
    container_name: bot_db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bot
    command: postgres -p 5432
    networks:
      - bot-network
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3.10.7-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - bot-network
    restart: always

networks:
  bot-network:
    name: bot-network
    external: true