spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: HappyBirthdayBot
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/bot
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    database: POSTGRESQL
  flyway:
    locations: classpath:db/migration
  sql:
    init:
      platform: postgres

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    virtualhost: /
    port: ${RABBIT_PORT:15672}
    username: guest
    password: guest
    exchange: rabbitmq.exchange
    queue: rabbitmq.queue
    routing-key: rabbitmq.routingkey
    reply:
      timeout: 60000
    concurrent:
      consumers: 1
    max:
      concurrent:
        consumers: 1

server:
  port: 8081